name: books_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # لإدارة الحالة
  provider: ^6.1.1

  # للتعامل مع HTTP وREST APIs
  http: ^0.13.6

  # لاختيار الصور من المعرض والكاميرا
  image_picker: ^0.8.9

  # للتعرف على نوع الملف MIME (لرفع الصور)
  mime: ^1.0.2

  # لمعالجة أنواع محتوى HTTP
  http_parser: ^4.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
